language: node_js
node_js:
- '0.10'
services:
- mongodb
env:
  global:
    secure: qIMPPradztF6veoAY7D1GA25BRndKsfIHdkbVvDYXoqr9IseJEKzLj0ovy/nPd/5fcxzG2D/+I6dNIX7tLaowv82BVff0dmBgmcklY5sLphgIaUEuqDpvduJoA+29SyP0oQzEV8SjLnqbXCzCmV1uLeNe1+VgtLkRZKnCMQNRfY=
